app.services.greeting.message: Hello

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:54325/company
    driver-class-name: org.postgresql.Driver